# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28eded8d7187b0e749e3daa08eea55382d1c4a0324a8251e1c6a3a78f2c39ab0e237c9ad6ac1e2fd8d61a5124ff1ea0f395756a432ef7e885dae8cacef12d252

test:
  secret_key_base: 984fe1fe8860f99675536b7f4cfa8b50d0a842df934cbb2fb6267b0507b014b21e84a3fa2b78342d8bdf64253e3f647ab5059ca68f01cc9098cb030961102170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
